module.exports = {
    nombre: 'Luke Skywalker',
    altura: '172',
    masa: '77',
    color_cabello: 'blond',
    color_piel: 'fair',
    color_ojos: 'blue',
    fecha_nacimiento: '19BBY',
    genero: 'male',
    planetas: 'https://swapi.py4e.com/api/planets/1/',
    peliculas: [
        'https://swapi.py4e.com/api/films/1/',
        'https://swapi.py4e.com/api/films/2/',
        'https://swapi.py4e.com/api/films/3/',
        'https://swapi.py4e.com/api/films/6/',
        'https://swapi.py4e.com/api/films/7/',
    ],
    especies: ['https://swapi.py4e.com/api/species/1/'],
    vehiculos: [
        'https://swapi.py4e.com/api/vehicles/14/',
        'https://swapi.py4e.com/api/vehicles/30/',
    ],
    naves: [
        'https://swapi.py4e.com/api/starships/12/',
        'https://swapi.py4e.com/api/starships/22/',
    ],
    fecha_creacion: '2014-12-09T13:50:51.644000Z',
    fecha_edicion: '2014-12-20T21:17:56.891000Z',
    url: 'https://swapi.py4e.com/api/people/1/',
};
